### ISSUE TITLE
Vários registration_id para o mesmo usuário

### ISSUE THREAD

**Issue by jocemarfg** [AudasiTI/infosoil#18]
-- Table: user_account_gcm

-- DROP TABLE user_account_gcm;

CREATE TABLE user_account_gcm
(
  registration_id bigint NOT NULL DEFAULT nextval('user_account_reg_id_registration_id_seq'::regclass),
  registration_token character varying(360),
  user_account_id bigint,
  CONSTRAINT pk_user_account_reg_id PRIMARY KEY (registration_id),
  CONSTRAINT fk_user_account_reg_id_user_account FOREIGN KEY (user_account_id)
      REFERENCES user_account (user_account_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
WITH (
  OIDS=FALSE
);
ALTER TABLE user_account_gcm
  OWNER TO postgres;

**Comment by jocemarfg** [comment]
-- Sequence: user_account_reg_id_registration_id_seq

-- DROP SEQUENCE user_account_reg_id_registration_id_seq;

CREATE SEQUENCE user_account_reg_id_registration_id_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 1
  CACHE 1;
ALTER TABLE user_account_reg_id_registration_id_seq
  OWNER TO postgres;

**Comment by adelinojatai** [comment]
ALTER TABLE user_account
  DROP COLUMN android_token;
ALTER TABLE user_account
  DROP COLUMN ios_token;

**Comment by adelinojatai** [comment]
Foi feito o teste e verificado que o mesmo usuário pode possuir mais de um token.
