### ISSUE TITLE
Não limpa os laudos carregados quando um novo é escolhido

### ISSUE THREAD

**Issue by adelinojatai** [AudasiTI/infosoil#20]
Foi verificado que se um laudo for selecionado e carregado na tela de importação e depois outro laudo for selecionado e carregado, ao inverso de ser exibido so o ultimo que foi carregado, são exibidos os dois laudos.

**Comment by adelinojatai** [comment]
Esta limpando os arquivos porém não zera o contador da barra de progresso.

**Comment by warteruzannan** [comment]
* Faz a importação de todos os laudos selecionados.

**Comment by adelinojatai** [comment]
Foi feita a correção e esta limpando os arquivos e zerando a barra de progresso
