### ISSUE TITLE
Refactoring Importação de laudos

### ISSUE THREAD

**Issue by jocemarfg** [AudasiTI/infosoil#26]
Realizar refactoring na importação de laudos no INFOsoil Admin:

- [x] Validar arquivos para a importação: exibir janela popup informando os arquivos que estão inválidos e o motivo;
- [x] Limpar o input file;
- [x] Melhorar fonte da tabela;
- [x] Otimizar carregamento dos arquivos e comportamento da barra de progresso;

**Comment by warteruzannan** [comment]
Criação do Laudo - Feito

**Comment by warteruzannan** [comment]
Melhoria na fonte da tabela
Obs: Verificar, porquê eu não tenho um bom trabalho artístico

**Comment by warteruzannan** [comment]
Arquivos para importação validados!

**Comment by warteruzannan** [comment]
Limpar input file - feito!

**Comment by warteruzannan** [comment]
Barra de progresso melhorada!

**Comment by adelinojatai** [comment]
* A popup de arquivos com falha não possui um X para fechar
* Deverá ser limpada a lista de arquivos carregados, quando for clicado em escolher arquivos e então a lista de arquivos deve ser preenchida somente com os selecionados nesse momento.
* Ao carregar vários arquivos com falha esta ocorrendo de exibir o nome somente de um arquivo

**Comment by adelinojatai** [comment]
Feita a correção das falhas

**Comment by adelinojatai** [comment]
Foi verificado que os arquivo anexo não esta sendo validado e nem carregado

**Comment by adelinojatai** [comment]
Será finalizado pois o erro citado foi registrado em outra atividade.
