### ISSUE TITLE
Melhorar responsividade do INFOsoil Admin

### ISSUE THREAD

**Issue by jocemarfg** [AudasiTI/infosoil#29]
Algumas páginas do INFOsoil Admin estão sem responsividade.

Apesar de não ser o foco do aplicativo, caso seja possível deixá-lo mais responsivo, para consultar de laudos importados via aplicativo, será importante.

**Comment by adelinojatai** [comment]
Ficou exibindo corretamente com uma pequena falha nos botões da tela de importação que são muito grandes e cortam o nome
