### ISSUE TITLE
Validar arquivo durante o carregamento e exibir relatório de erros

### ISSUE THREAD

**Issue by jocemarfg** [AudasiTI/infosoil#30]
- Os arquivos selecionar para importação devem ser validados e caso possuam erros, devem exibidos exibidos em tela popup com **botão de OK** e **opção de exportar para pdf**;

- As validações devem ser:
 - Se o e-mail do cliente ou solicitante está presente;
 - Se a coluna id está presente;
 - Se a coluna laudo está presente;

- No caso do laudo foliar, deve ser verificado se a coluna Cultura está preenchida e se corresponde a um dos seguintes itens:

> "MILHO"
> "SOJA"
> "FEIJÃO"
> "ALGODÃO"
> "CANA-DE-AÇUCAR"
> "SOJA C/ PECÍOLO"
> "EUCALIPTO"
> "ARROZ"
> "SORGO"
> "CAFÉ"

**Comment by adelinojatai** [comment]
Nem esta validando a coluna id e nem os dados de email, se existem ou não.

**Comment by adelinojatai** [comment]
Não validou e nem carregou o arquivo folha 1.xls

**Comment by adelinojatai** [comment]
Foi feito a correção dos erros mencionados
